apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: code-testmatrix-nov6 
  janus-idp.io/tekton: code-testmatrix-nov6
  backstage.io/kubernetes-id: code-testmatrix-nov6
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: code-testmatrix-nov6
resources: 
- application-dev.yaml