apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: code-testmatrix-nov6
  janus-idp.io/tekton: code-testmatrix-nov6
  backstage.io/kubernetes-id: code-testmatrix-nov6
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: code-testmatrix-nov6
resources: 
- initialize-namespace.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
