---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: code-testmatrix-nov6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: code-testmatrix-nov6 
  name: code-testmatrix-nov6
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi